# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
sudo: false
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
r_github_packages:
  - ropensci/rgbif
  - ropensci/rvertnet
  - ropensci/rinat
addons:
  apt:
    packages:
      - libv8-dev
after_success:
  - Rscript -e 'library(covr);codecov()'
